[package]
name = "split-accum"
authors = ["Andrew Whitehead <cywolf@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
bls12_381_plus = { version = "0.8", features = ["std"] }
rand = "0.8"
sha2 = "0.10"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "accum"
harness = false
